export const SET_ALBUMS = "SET_ALBUMS";
export const SET_ALBUM_STATE_FROM_STORAGE = "SET_ALBUM_STATE_FROM_STORAGE";
export const SET_DISPLAYED_ALBUMS = "SET_DISPLAYED_ALBUMS";
export const SET_ERROR = "SET_ERROR";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
